### ISSUE TITLE
Strengthen small scale contents

### ISSUE THREAD

**Issue by hfu** [unvt/naru#2]
# background
The current vector tile schema used in `naru` is weak in small scale because it was sourced from UN internal implementation that uses UN internal 

# zoom level shift
We may be able to add more road and city name data in smaller scale.

We will be modifying https://github.com/unvt/naru/blob/master/modify.js. 

## current implementation of place
- minzoom = 6 if capital
- minzoom = 8 if city
- minzoom = 10 if town
- minzoom = 12 if village
- minzoom = 14 otherwise

## current implementation of road
as in https://github.com/unvt/naru/blob/9c951a7f90c354576d0153efb89e9c4d1c7e5169/modify.js#L208-L242
 
# contour lines
We may be able to add contour lines using SRTMGL1v003 (30m GSD) from https://e4ftl01.cr.usgs.gov/MEASURES/SRTMGL3.003/2000.02.11/ .

The command will be something like: 

```zsh
gdal_contour -i 10 -snodata -32768 -a alti [raster file path] [shapefile path]
```

**Comment by hfu** [comment]
Regarding contour lines, [this article](https://medium.com/@ralucagnicola/how-to-create-a-3d-web-map-of-contour-lines-68d1e1491a2b) looks useful.

**Comment by JinIgarashi** [comment]
@hfu I am adjusting some scale level for style.json in my branch [feature/adjust_style](https://github.com/watergis/naru/tree/feature/adjust_style).

Let me write in Japanese from here.

自分のブランチで低縮尺の時の表示を少し修正しています。いい感じになったらPR出したいと思います。
色々調べながらやっていますが、とりあえず、

- natureとlanduseを別レイヤに分けて、ズームレベルを少し落としました。natureのスタイルの色をそれっぽく緑色にしてみました。Landuseにも自然っぽいデータがあったのでそれらはnatureのままにしています。
- highwayのtrunkのレベルを落としました。

あと最終的なPRでは消しますが、中のデータを確認するために一時的にmapbox-gl-inspectツールを入れています。

ちなみにレベル8だとこんな感じです。道路と自然だけですが少し情報が増えました。
![image](https://user-images.githubusercontent.com/2639701/106381160-407f7200-63fa-11eb-9075-47f90bdd94ec.png)

30MBくらいで小さなルワンダのデータでテストしてるのですが、ルワンダにはないデータとかあったりしそうでちょっとその辺が不安です。テスト用に使える程よいサイズのおすすめの国のデータってあるでしょうか？

**Comment by hfu** [comment]
多分アルファベット順で若いからだと思いますが、アルバニアはテスト変換で使われることがよくあるように思います。なお、私はプロジェクトでアルバニアをカウンターパートにしています。あと、デモで綺麗な見栄えになりやすいのは島国で、スリランカなどは見栄えの良いデモがサイトを作れると言う点でも魅力的だと思いました。

**Comment by JinIgarashi** [comment]
なるほど。アルバニアとスリランカですね。試してみます。
UNVTのタイルセットを見ていて、lv1-lv5まではレイヤがないような気がしています。低ズームレベルの時は対象の国以外も含めて全世界のNatural earthの国境とか海・湖、海岸線、国名当たりを出すようにしたらどうかなと思ったのですが、どうでしょうか？

なんとなく、Nodejsのモジュールを別リポジトリで作って、それをRakefileから`rake inet:download`と`rake tiles`コマンドの中で呼び出してあげるのが良さそうな気がしています。

**Comment by hfu** [comment]
Natural Earth の国境表現については、必ずしも全ての国がハッピーとは限らないというところだけが気になります。国境線については、入れないか、またはオプトアウトできるようにしていただけると、より広い範囲の方々にリーチできるのではないかと思っています。水部や国名についてはそういったセンシティビティはより少ないので、安心して進められそうですね。

**Comment by JinIgarashi** [comment]
Natural EarthからダウンロードしてGeoJSONにするモジュールがなんとかできました。

https://github.com/watergis/ne2geojson

こんな感じでパイプで繋いでいくとNatural Earthのmbtiles作れます。
```
node src/index.js download $(pwd)/data $(pwd)/define.json | node src/index.js convert | tippecanoe --no-feature-limit --no-tile-size-limit --force --simplification=2 --maximum-zoom=5 --base-zoom=5 --hilbert --output=tiles.mbtiles
```

`define.json`ファイルの中でデータを削除したり追加したりできます。

できたmbtiles添付します。

[tiles.mbtiles.zip](https://github.com/unvt/naru/files/5911622/tiles.mbtiles.zip)

vt-optimizerにかけたら一応赤色になってなかったので大丈夫かなと

```
Vector Tile Info
Zoom levels:  0,
Format:  pbf
Center:  16.875000,44.951199,5
Layers: 

• administrative
• boundary
• coastline
• glaciated_areas
• land
• ocean
• place
• playas
• populated_area
• urban_area
• water

Vector Tile Summary
Zoom level  Tiles  Total level size (KB)  Average tile size (KB)  Max tile size (KB)   
----------  -----  ---------------------  ----------------------  ------------------  -
1           4      157.8837890625         39.470947265625         64.26953125         ✓
2           16     195.6708984375         12.22943115234375       52.8681640625       ✓
3           64     1461.28515625          22.83258056640625       131.7138671875      ✓
4           256    1974.5380859375        7.713039398193359       82.3173828125       ✓
5           1024   7915.0283203125        7.729519844055176       268.3544921875      ✓
```

**Comment by JinIgarashi** [comment]
Natural Earth版のUNVTなんとなくできました。
https://watergis.github.io/ne2geojson/#2/0/0

Hoconでのスタイルを調整中です。思ったんですが、unvt/naruに組み込むのでなく、どっかにnatural earth版のmbtilesを置いておいて、それをwgetしてtile-joinして使うみたいな感じが良いような気がしています。元データのシェープファイルは200MBくらいとそこそこ大きいですが、レベル7まで作ったとして30MBくらいなので、ダウンロードも大したことなさそうです。

UNVTに複数のstyle.jsonをマージするモジュールが必要な気がしますね。

そうすればデータソースごとに個別に作っておいてmbtilesとstyle.jsonをいるものだけマージして使うみたいなことができそうです。

**Comment by JinIgarashi** [comment]
Natural Earth版UNVTのスタイル大体出来ました。
https://watergis.github.io/ne2geojson/#2.44/0.31/18.86

国の名前を出すのが思ったよりも大変で手こずりました（特にフィジー）。一番大きい面積のポリゴンの重心に国名を出すような感じにしました。

https://github.com/watergis/ne2geojson/blob/main/config/config.json

このファイルでタイルに入れるデータを設定できるようにしてあります。ただ国のデータを消すと国名も消えてしまうので、国境はhoconの`ne-ls-country.conf`を消すみたいな対応になる感じかなと思っています。

hoconの命名は、OSM版と分けるために、ファイル名の頭に`ne`とつけるようにしています。

ルワンダとケニアのUNVTにNatural Earthのをマージしてどうなるか試してみます。

**Comment by JinIgarashi** [comment]
@hfu OSMのUNVTにNatural Earthをレベル1-6で追加してみました。OSMのレイヤの縮尺も若干調整しました。ルワンダの水道公社のGithubにリポジトリ作りました（https://github.com/WASAC/naru）。

あと中縮尺の時に建物ポリゴンが見にくくなってしまっていたので、shadow/outlineを復活させて、３Dの色を少し調整しました。これで大丈夫そうでしたら、unvt/naruの方にOSMスタイル修正のみPR投げます。
naru本体にはNatural Earthは入れない方がいい気がするので

ルワンダ版のUNVT＋Natural Earth
https://wasac.github.io/naru

**Comment by JinIgarashi** [comment]
@hfu I created PR (https://github.com/unvt/naru/pull/9) for the above changes of style.
