### ISSUE TITLE
建物を OpenMapTiles と同様に立ち上げるように改修する（作業記録）

### ISSUE THREAD

**Issue by hfu** [unvt/naru#5]
OpenMapTiles ではどのようにしているか以前 @smellman にヒントをいただいていたように記憶しているので、それを実装してみます。（どこでヒントをいただいていたか見失っているので、改めて教えてもらえると嬉しいです。> @smellman ）

- [x] 変更前の naru の pg-building*.conf の実装について、メモを残しておく
- [ ] naru ベースのタイルで必要な属性がタイルに埋まっていることを確認する
- [ ] hocon/pg-building-*.conf を改修する

kokoromi-western-balkans* で反映することを目指しています。

**Comment by hfu** [comment]
# 変更前の `naru` の pg-buidling*.conf の実装
## [layers.conf](https://github.com/unvt/naru/blob/master/hocon/layers.conf)
```hocon
  { include pg-building-shadow }
  { include pg-building }
  { include pg-building-train-station }
  { include pg-building-outline }
```
二次元グラフィックスで三次元っぽく見せるように黒く縁取りをするということを狙った設計でした。

鉄道駅については、建物の中に鉄道が入っているパターンがあったので、**ある程度拡大すると半透過にする**という工夫をしており、そのために別レイヤとしていました。

Mapbox Style を記述する原則は「下に書くものから順番に書いていく」というものです。それぞれのレイヤの記述内容について、順番にみていきます。

なお、この layers.conf で使っているレイヤ id の命名規則は、概ね次のような感じです。

```
{ジオメトリタイプ}-{OSMタグ}-{レイヤ固有名}
```

ジオメトリタイプは、ベクトルタイルに含まれているジオメトリの型です。次の３種類にしています。

- pt: Point 
- ls: LineString
- pg: Polygon

MultiLineString は ls で、MultiPolygon は pg で扱っている場合が多いです。

OSM タグは、今回の場合は building です。naru で作るベクトルタイルは、**OSM のタグ構造を比較的そのまま素直に取り入れる**ようになっているので、Mapbox Style の filter でうまくひっかけて判別しています。他のベクトルタイルでは、クラス構造（あるいはリレーショナルデータベースのテーブル）を作ってマッピングをしていることがあるかもしれませんが、naru の基本的な考え方は、回避不可能な必要が生じるまでは、凝ったマッピングはしない、というものです。

## [pg-building-shadow](https://github.com/unvt/naru/blob/master/hocon/pg-building-shadow.conf)
```hocon
id: pg-building-shadow
type: fill
source: v
source-layer: building
minzoom: 16
filter: [
  match
  [
    geometry-type
  ]
  [
    Polygon
    MultiPolygon
  ]
  [
    match
    [
      get
      layer
    ]
    [
      "-1"
      "-2"
      "-3"
      "-4"
      "-5"
    ]
    false
    [
      match
      [
        get
        building
      ]
      [
        train_station
        roof
      ]
      false
      true
    ]
  ]
  false
]
paint: {
  fill-color: [
    rgb
    131
    124
    124
  ]
  fill-translate: [
    2
    2
  ]
}
```

このレイヤは、建物の影を描画するためのもので、`paint` にある `fill-translate` で、もとのジオメトリから (2, 2) ピクセル分ずらすことで、この後建物本体が描かれたあとに影としてみられる微量の濃色部をつくります。

## [pg-building](https://github.com/unvt/naru/blob/8436aed5d65d23cd56b90fe25627ec73baba5ae0/hocon/pg-building.conf)
執筆現在最新のものは kokoromi-ke のために fill-extrusion  を使うように改修されているので、この改修前のものをコピーすると次の通りです。

```hocon
id: pg-building
type: fill
source: v
source-layer: building
filter: [
  match
  [
    get
    building
  ]
  [
    train_station
    roof
  ]
  false
  [
    match
    [
      geometry-type
    ]
    [
      Polygon
      MultiPolygon
    ]
    true
    false
  ]
]
paint: {
  fill-color: [
    match
    [
      get
      layer
    ]
    [
      "-1"
      "-2"
      "-3"
      "-4"
      "-5"
    ]
    [
      rgb
      238
      238
      238
    ]
    [
      rgb
      222
      215
      215
    ]
  ]
}
```
train_station と roof を外すという調整はしていますが、基本的には素直なポリゴン描画のスタイルになっています。

## [pg-building-train-station](https://github.com/unvt/naru/blob/master/hocon/pg-building-train-station.conf)
```hocon
id: pg-building-train-station
type: fill
source: v
source-layer: building
filter: [
  match
  [
    geometry-type
  ]
  [
    Polygon
    MultiPolygon
  ]
  [
    match
    [
      get
      building
    ]
    [
      train_station
      roof
    ]
    true
    [
      match
      [
        get
        public_transport
      ]
      station
      true
      false
    ]
  ]
  false
]
paint: {
  fill-color: [
    match
    [
      get
      layer
    ]
    [
      "-1"
      "-2"
      "-3"
      "-4"
      "-5"
    ]
    [
      rgb
      238
      238
      238
    ]
    [
      rgb
      222
      215
      215
    ]
  ]
  fill-opacity: [
    interpolate
    [
      linear
    ]
    [
      zoom
    ]
    16
    1
    17
    0.4
  ]
}
```
fill-opacity のところに、ズームによって透過率を変えるという expression を入れているところが特徴です。つまり、
```lisp
(interpolate (linear) (zoom) 16 1 17 0.4)
```
という表現を入れることで、ズームレベルが17になったら opacity を 0.4 に下げるということをしています。

雑談になりますが、expression は Lisp で書きたくなりますね。[Mapbox Style の仕様](https://docs.mapbox.com/help/tutorials/mapbox-gl-js-expressions/#syntax)にも、次のとおり書いてあります。

> Mapbox GL JS expressions uses a Lisp-like syntax, represented using JSON arrays. 

## [pg-building-outline](https://github.com/unvt/naru/blob/master/hocon/pg-building-outline.conf)
```
id: pg-building-outline
type: line
source: v
source-layer: building
minzoom: 14
include _polygon
paint: {
  line-color: [
    rgb
    183
    174
    174
  ]
  line-width: 1
}
```
フチを強調するためのアウトラインです。

**Comment by hfu** [comment]
# naru ベースのタイルで必要な属性がタイルに埋まっていることを確認する
naru ベースのタイルで建物を表示している典型例は、次の通りです。
https://optgeo.github.io/kokoromi-ch/#16.54/46.202719/6.142072

これを Chrome で表示して、Mapbox Vector Tiles のエクステンションを使ってタイルの内容をダンプしたものを見ることにより、

- building:levels

というキーで例えば "7" という数値が「文字列で」入っていることを確認しました。

このキーを Google で検索することにより、例えば
https://wiki.openstreetmap.org/wiki/JA:%E5%9F%BA%E6%9C%AC%E7%9A%84%E3%81%AA3D%E3%81%AE%E5%BB%BA%E7%89%A9
といったドキュメントを見ることができます。

## ところで
ところで、音によって建物の高さを変えるという変な実装を見つけました。
https://docs.mapbox.com/jp/mapbox-gl-js/example/dancing-buildings/

**Comment by smellman** [comment]
高さってこれかな？
https://github.com/openmaptiles/openmaptiles/blob/master/layers/building/building.sql#L101
OpenMapTilesではlevels*3.66としています。
これが「データベース」に入ってるというのがポイントです。

> ところで、音によって建物の高さを変えるという変な実装を見つけました。

これに似たようなものを作ろうと考えてた...

**Comment by hfu** [comment]
@smellman unvt は OSM のデータモデルに忠実に、ブラウザの能力を信じる方向で「スタイル」に実装していました。いちおう動いています！ありがとう smellman! 
https://unvt.github.io/mame/#15.68/41.322155/19.824567/-85.6/57
![ 2020-06-29 22 10 59](https://user-images.githubusercontent.com/18297/86010001-cf3ba300-ba55-11ea-86d9-48d9d0d13809.jpg)

**Comment by JinIgarashi** [comment]
@hfu mameのリポジトリを参考にして、３Dの建物の高さのスタイルを適用する[PR](https://github.com/unvt/naru/pull/7)を出してみました。問題なさそうならマージしていただければと思います。
