### ISSUE TITLE
style.jsonのルートパスの変更方法

### ISSUE THREAD

**Issue by JinIgarashi** [unvt/naru#6]
@hfu 

以前作っていただいたケニアとルワンダのUNVTのタイルを定期的に最新のOSMにしていきたいと思って、unvt/naruのソースコードを見ています。
とりあえずCIでデータの更新を自動化したいと思い、[watergis/naruのfeature/add_docker](https://github.com/watergis/naru/tree/feature/add_docker)ブランチでDockerでタイルをビルドしたりできるようにしました。

一点style.jsonのルートパスを変える方法がちょっとわからなく、教えていただけないでしょうか？

デフォルトだと`rake style`で作ると`http://localhost:9966/`がstyle.jsonに設定されるのですが、これをgithub pagesなどの他のルートパスに環境変数などで動的に変えるようにしたいです。

source.confの中で`${site_root}`と書いてるので、環境変数にsite_rootを設定すればいけるのかと思いましたが、だめでした。

ちなみに、このDocker版`unvt/naru`にPRとか出しても大丈夫でしょうか？

あと、nodejsが入っているDockerイメージからビルドするようにしたところ、デフォルトでosmiumをapt installしようとすると古いバージョンでしかインストールできず、自分でコンパイルする方法にしています。最新版のビルド済みのosmiumパッケージをDockerにインストール方法ってあるでしょうか？

**Comment by hfu** [comment]
'site_root' は hocon/_root.conf でセットしています。とり急ぎ！

**Comment by JinIgarashi** [comment]
ありがとうございます。

Rakefileの中で下のようにしたらsite_rootを環境変数で設定できました。

```ruby
SITE_ROOT = ENV['SITE_ROOT'] || 'http://localhost:9966'

desc 'build style.json from HOCON descriptions'
task :style do
  require 'json'
  sh "site_root=#{SITE_ROOT} parse-hocon hocon/style.conf > docs/style.json"
  center = JSON.parse(File.read('docs/zxy/metadata.json'))['center'].split(',')
    .map{|v| v.to_f }.slice(0, 2)
  style = JSON.parse(File.read('docs/style.json'))
  style['center'] = center
  File.write('docs/style.json', JSON.pretty_generate(style))
  sh "gl-style-validate docs/style.json"
end
```

**Comment by JinIgarashi** [comment]
この件、[PR](https://github.com/unvt/naru/pull/8)出してみました

**Comment by JinIgarashi** [comment]
マージありがとうございます。Issueクローズしますね
